name: Build and Deploy Spring Boot to AWS EC2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # 새로 추가된 부분
    - name: Grant execute permission to gradlew
      run: chmod +x ./backend/blob/aec455ec4b37b72d9bb354db3f2fcca1c7d8f2e9/gradlew
    # 여기까지

    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build

# https://github.com/living-in-seoul/backend/blob/aec455ec4b37b72d9bb354db3f2fcca1c7d8f2e9/gradlew
