name: Build and Deploy Spring Boot to AWS EC2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # 새로 추가된 부분
    - name: Grant execute permission to gradlew
      run: chmod +x ./gradlew
    # 여기까지

    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build

    - name: Deploy Prod use SCP
      uses: appleboy/scp-action@master
      with:
        username: ubuntu
        host: ${{ secrets.HOST }}
        key: ${{ secrets.PASSWORD }}
        source: "./build/libs/*.jar"
        target: "/home/ubuntu/deploy"
        strip_components: 2
          
          
